# Generated by Django 3.1.4 on 2021-01-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('company', '0002_companymod_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripekey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripekey', to='company.companyadmin')),
                ('userkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripekey', to='djstripe.customer')),
            ],
        ),
    ]
