# Generated by Django 3.1.4 on 2021-01-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_stripekey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stripekey',
        ),
    ]
